VlomsFont = surface.CreateFont( "VlomsFont", {
	font = "Trebuchet MS",
	size = 24,
	weight = 900,
	blursize = 0,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false,
} )